# Performing Principal Component Analysis (PCA) - Lab

## Introduction

Now that you have high level overview of PCA as well as some of the details in the algorithm itself, its time to practice implementing PCA on your own using the NumPy package. 

## Objectives

You will be able to:
    
* Implement PCA from scratch using NumPy

## Import the Data

To start, import the data stored in the file 'foodusa.csv'.

In [5]:
#Your code here
import pandas as pd
import numpy as np 
food = pd.read_csv('foodusa.csv',index_col=0)

In [6]:
food.head(2)

Bread  Burger  Milk  Oranges  Tomatoes
City                                             
ATLANTA     24.5    94.5  73.9     80.1      41.6
BALTIMORE   26.5    91.0  67.5     74.6      53.3

## Normalize the Data

Next, normalize your data by subtracting the feature mean from each of the columns

In [10]:
#Your code here
mean_centered = food-food.mean()

## Calculate the Covariance Matrix

The next step for PCA is to calculate to covariance matrix for your normalized data. Do so here.

In [24]:
#Your code here
cov_matrix = np.cov([mean_centered.Bread,mean_centered.Burger,mean_centered.Milk,mean_centered.Oranges,mean_centered.Tomatoes])

In [26]:
cov_matrix.shape

(5, 5)

## Calculate the Eigenvectors

Next, calculate the eigenvectors for your covariance matrix.

In [29]:
#Your code here
eigenvalue, eigenvector = np.linalg.eig(cov_matrix)
eigenvector

array([[-0.02848905, -0.16532108, -0.96716354, -0.18972574,  0.02135748],
       [-0.2001224 , -0.63218494,  0.24877074, -0.65862454,  0.25420475],
       [-0.0416723 , -0.44215032,  0.03606094,  0.10765906, -0.88874949],
       [-0.93885906,  0.31435473, -0.01521357, -0.06904699, -0.12135003],
       [-0.27558389, -0.52791603, -0.03429221,  0.71684022,  0.36100184]])

In [30]:
eigenvalue

array([218.99867893,  91.72316894,   3.02922934,  20.81054128,
        37.66268981])

## Sorting the Eigenvectors to Determine Primary Components

Great! Now that you have the eigenvectors and their associated eigenvalues, sort the eigenvectors based on their eigenvalues!

In [36]:
#Your code here
ind = np.argsort(eigenvalue)[::-1]
sorted_eigenvector = eigenvector[:,ind]

In [37]:
sorted_eigenvector

array([[-0.02848905, -0.16532108,  0.02135748, -0.18972574, -0.96716354],
       [-0.2001224 , -0.63218494,  0.25420475, -0.65862454,  0.24877074],
       [-0.0416723 , -0.44215032, -0.88874949,  0.10765906,  0.03606094],
       [-0.93885906,  0.31435473, -0.12135003, -0.06904699, -0.01521357],
       [-0.27558389, -0.52791603,  0.36100184,  0.71684022, -0.03429221]])

## Reprojecting the Data

Finally, reproject the dataset using your eigenvectors. Reproject the dataset down to 2 dimensions.

In [38]:
#Your code here
transformed = sorted_eigenvector.dot(mean_centered.T).T
transformed

array([[ 1.11063671e+01,  1.47313493e+01, -1.41720384e+01,
         1.85530932e+00, -1.31519693e+01],
       [ 1.21900301e+00,  2.14498941e+01, -7.19007196e+00,
        -1.44250494e-01, -1.85096828e+01],
       [-1.22936562e+01, -4.73286484e+00, -2.84276415e+00,
        -1.45351480e+00, -5.90817824e+00],
       [-4.27410508e+00, -4.95746329e+00,  1.50456490e+00,
        -7.78972241e-01,  1.55082192e+01],
       [-2.08570219e+00,  1.77071529e+00,  2.26283823e+00,
        -3.23048970e+00,  4.48154292e+00],
       [ 2.02322957e+00, -4.83130671e+00, -6.11053639e+00,
         3.51881382e+00, -7.79622091e+00],
       [ 7.65139684e-01, -5.78241861e+00,  1.10305914e+01,
         2.06281561e+00,  4.46446433e+00],
       [ 5.01990281e+00, -7.08302707e+00,  4.06579025e+00,
        -1.07688088e+00,  1.49042564e+01],
       [-5.28963606e+00, -7.18560259e+00,  9.68250581e+00,
         2.48951246e+00,  1.42270390e-01],
       [-2.02949124e+01, -2.18073279e+01, -1.85701795e+01,
        -3.80426303e+00

## Summary

Well done! You've now coded PCA on your own using NumPy! With that, it's time to look at further application of PCA.